services:
  api:
    build:
      context: .
      dockerfile: CiviCore.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - civicore_public_media:/app/wwwroot/public-media
      - civicore_private_media:/app/App_Data/PrivateMedia

  web:
    build:
      context: ./CiviCore.Web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./CiviCore.Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  civicore_public_media:
  civicore_private_media:
